default-remote: local
remotes:
  images:
    addr: https://images.linuxcontainers.org
    protocol: simplestreams
    public: true
  local:
    addr: unix://
    public: false
  mirror-images:
    addr: https://mirrors.tuna.tsinghua.edu.cn/lxc-images/
    protocol: simplestreams
    public: true
aliases: {}
