#!/bin/bash

SELF_UUID=""
# CONNECTION_UUID="0e593986-54ac-4fed-9ed5-435bf4592908"
DLUT_UUID="0e593986-54ac-4fed-9ed5-435bf4592908"

UP_CMD="dae run --disable-timestamp -c /home/jc/.config/dae/general/config.dae"
UP_DLUT_CMD="dae run --disable-timestamp -c /home/jc/.config/dae/dlut/config.dae"
DOWN_CMD="killall dae"

# if [[ "$SELF_UUID" =~ "$CONNECTION_UUID" ]]; then
# 	logger "Current connection do not need start dae."
# else
# if [[ "$DLUT_UUID" =~ "$CONNECTION_UUID" ]]; then
# 	logger "Start DLUT"
# 	case "$2" in
# 	up | vpn-up)
# 		exec $UP_DLUT_CMD
# 		;;
# 	down | vpn-down)
# 		exec $DOWN_CMD
# 		;;
# 	esac
# else
# 	logger "Start General"
# 	case "$2" in
# 	up | vpn-up)
# 		exec $UP_CMD
# 		;;
# 	down | vpn-down)
# 		exec $DOWN_CMD
# 		;;
# 	esac
# fi
# fi
