[mgr]
cwd = { fg = "#179299" }

# Find
find_keyword  = { fg = "#df8e1d", italic = true }
find_position = { fg = "#ea76cb", bg = "reset", italic = true }

# Marker
marker_copied   = { fg = "#40a02b", bg = "#40a02b" }
marker_cut      = { fg = "#d20f39", bg = "#d20f39" }
marker_selected = { fg = "#1e66f5", bg = "#1e66f5" }

# Count
count_copied   = { fg = "#eff1f5", bg = "#40a02b" }
count_cut      = { fg = "#eff1f5", bg = "#d20f39" }
count_selected = { fg = "#eff1f5", bg = "#1e66f5" }

# Border
border_symbol = "│"
border_style  = { fg = "#8c8fa1" }

# Highlighting
syntect_theme = "~/.config/yazi/Catppuccin-latte.tmTheme"

[tabs]
active   = { fg = "#eff1f5", bg = "#4c4f69" }
inactive = { fg = "#4c4f69", bg = "#bcc0cc" }
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[mode]
normal_main = { fg = "#eff1f5", bg = "#1e66f5", bold = true }
normal_alt  = { fg = "#1e66f5", bg = "#bcc0cc" }
select_main = { fg = "#eff1f5", bg = "#40a02b", bold = true }
select_alt  = { fg = "#40a02b", bg = "#bcc0cc" }
unset_main  = { fg = "#eff1f5", bg = "#dd7878", bold = true }
unset_alt   = { fg = "#dd7878", bg = "#bcc0cc" }

[indicator]
parent  = {}
current = {}
preview = { underline = true }
padding = { open = "", close = "" }

[status]
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Progress
progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#1e66f5", bg = "#bcc0cc" }
progress_error  = { fg = "#d20f39", bg = "#bcc0cc" }

# Permissions
perm_sep   = { fg = "#8c8fa1" }
perm_type  = { fg = "#1e66f5" }
perm_read  = { fg = "#df8e1d" }
perm_write = { fg = "#d20f39" }
perm_exec  = { fg = "#40a02b" }

[input]
border   = { fg = "#1e66f5" }
title    = {}
value    = {}
selected = { reversed = true }

[pick]
border   = { fg = "#1e66f5" }
active   = { fg = "#ea76cb" }
inactive = {}

[tasks]
border  = { fg = "#1e66f5" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "#ccd0da" }
cand            = { fg = "#179299" }
rest            = { fg = "#7c7f93" }
desc            = { fg = "#ea76cb" }
separator       = "  "
separator_style = { fg = "#acb0be" }

[help]
on      = { fg = "#ea76cb" }
run     = { fg = "#179299" }
desc    = { fg = "#7c7f93" }
hovered = { bg = "#acb0be", bold = true }
footer  = { fg = "#bcc0cc", bg = "#4c4f69" }

[filetype]
rules = [
  # Images
  { mime = "image/*", fg = "#179299" },

  # Media
  { mime = "{audio,video}/*", fg = "#df8e1d" },

  # Archives
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#ea76cb" },

  # Documents
  { mime = "application/{pdf,doc,rtf}", fg = "#179299" },

  # Special files
  { url = "*", is = "orphan", bg = "#d20f39" },
  { url = "*", is = "exec", fg = "#40a02b" },

  # Fallback
  { url = "*", fg = "#4c4f69" },
  { url = "*/", fg = "#1e66f5" },
]
