[mgr]
linemode = "size"

[preview]
tab_size = 2
max_width = 1000
max_height = 1000

[opener]
edit = [
  { run = 'nvim %s', desc = "nvim", block = true, for = "unix" },
  { run = 'neovide %s', desc = "Neovide", orphan = true, for = "unix" },
]
play = [
  { run = 'mpv %s', desc = "mpv", orphan = true, for = "unix" },
  { run = "mediainfo %s1; echo 'Press enter to exit'; read _", block = true, desc = "Show media info", for = "unix" },
]
archive = [
  { run = 'ya pub extract --list %s', desc = "Extract here" },
  { run = 'unrar x %s1', desc = "Unrar here", block = true, for = "unix" },
]
appimage = [
  { run = '%s1', desc = "Run AppImage", orphan = true, for = "unix" },
]

[open]
prepend_rules = [
  { url = "*.{AppImage,appimage}", use = [ "appimage", "reveal" ] },
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "extract", "reveal", "archive" ] },
]

[plugin]
prepend_previewers = [
  { mime = "application/{json,ndjson}", run = "json-pretty" },
  { mime = "audio/*", run = "exifaudio" },
  { mime = "text/csv", run = "miller" },
]
append_previewers = [
  { url = "*", run = "hexyl" },
]
