export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}
export XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
export XDG_STATE_HOME=${XDG_STATE_HOME:-$HOME/.local/state}
export OP_CONFIG_DIR=${OP_CONFIG_DIR:-$XDG_CONFIG_HOME/op}

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
